services:
  - type: web
    name: cricket-score-predictor
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "sh start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
